from: busybox
services:
  - gonkulatorlabs/rabbitmq:
      name: rabbitmq
      expose:
        - 5672:5672
  - kiasaki/alpine-postgres:
        name: postgres
        env:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=dev
        expose:
          - 5432:5432
expose:
  - 9000:9000
quiet: false
forward: true
tasks:
  env: env
  clean: npm run clean
  install: env
  test: npm run test
  lint: npm run lint
  build: npm run build
  start: npm start
  ci: .lint .test .build
