version: '2'

services:
  api:
    image: starhackit/api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=preprod-docker
    links:
      - postgres
      - rabbitmq
      - redis
  postgres:
    image: kiasaki/alpine-postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=preprod
  rabbitmq:
    image: gonkulatorlabs/rabbitmq
    expose:
      - "5672"
  redis:
    image: smebberson/alpine-redis
    expose:
      - "6379"
